
export const partnershipLogos = 
    [
        {
            imageSource:"/assets/images/partners/andes.jpg",
            link:"https://www.instagram.com/andesproadventures/?hl=es-la"
        },

        {
            imageSource:"/assets/images/partners/trekking.jpg",
            link:"https://www.fundaciontrekkingchile.cl/"
        },
        {
            imageSource:"/assets/images/partners/mahuida.jpg",
            link:"https://www.instagram.com/mahuidaexplorer/?hl=es-la"
        },
        {
            imageSource:"/assets/images/partners/defensa.png",
            link:"https://www.facebook.com/Los-Que%C3%B1es-Sin-Represas-826252444104043"
        },

        {
            imageSource:"/assets/images/partners/mapu-maule.png",
            link:"https://www.instagram.com/mapumaule/?hl=es-la"
        },
        {
            imageSource:"/assets/images/partners/vilches.jpeg",
            link:"https://www.camaraturismovilches.cl/"
        },
        {
            imageSource:"/assets/images/partners/arribs.png",
            link:"https://www.instagram.com/rioarribaong/?hl=es-la"
        },
        {
            imageSource:"/assets/images/partners/biota.jpg",
            link:"https://www.biotamaule.cl/"
        },
        {
            imageSource:"/assets/images/partners/camping-tricahue.jpeg",
            link:"https://www.instagram.com/campingrefugiotricahue/"
        },
        {
            imageSource:"/assets/images/partners/expedicion.png",
            link:"https://www.expedicionmaule.cl/"
        },
        {
            imageSource:"/assets/images/partners/millangeru.jpg",
            link:"https://www.instagram.com/millangeruexpediciones/?hl=es"
        },
        {
            imageSource:"/assets/images/partners/ong-andes.jpg",
            link:"https://andessustentable.cl/"
        },
        {
            imageSource:"/assets/images/partners/putagan.jpg",
            link:"https://www.putaganlibre.cl/"
        },
        {
            imageSource:"/assets/images/partners/refugio-tricahuee.jpeg",
            link:"https://www.refugio-tricahue.cl/"
        },
        {
            imageSource:"/assets/images/partners/rucamanke.png",
            link:"https://www.instagram.com/rucamankee/"
        },
        {
            imageSource:"/assets/images/partners/tricahue.jpg",
            link:"https://www.instagram.com/parquetricahue/?hl=es-la"
        },
        
    ]

